Repository HyacinthBots/LilyBot, pull requests merged in 2022-10, with the labels that each got.

#271 4.1.1
  build.gradle.kts
  docs/changelogs/4.1.1.md
  libs.versions.toml
  src/main/kotlin/org/hyacinthbots/lilybot/LilyBot.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MessageEdit.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
  src/main/resources/logback.groovy
  src/main/resources/logback.xml
Labels: PRT: release-staging

#274 Rewrite Reminders
  src/main/kotlin/org/hyacinthbots/lilybot/LilyBot.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/Cleanups.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/RemindMeCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/ReminderCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/RemindMeData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/ReminderData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/Migrator.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV1.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV3.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Reminders.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: T: enhancement, PRT: refactor

#278 Release 4.2.0
  build.gradle.kts
  docs/changelogs/4.2.0.md
  libs.versions.toml
  settings.gradle.kts
  src/main/kotlin/org/hyacinthbots/lilybot/LilyBot.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/Cleanups.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/GalleryChannelCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/GuildLeaveTimeCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/LogUploadingBlacklistCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/MetaCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/RemindMeCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/ReminderCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/RoleMenuCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/StatusCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/TagsCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/ThreadsCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/WarnCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/RemindMeData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/ReminderData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/Migrator.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV1.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV3.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Reminders.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: PRT: release-staging

#279 Remove nickname reject reasons and limit lengths
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/PublicUtilities.kt
Labels: PRT: Trivial

#285 Allow a default repo to be set on the GitHub commands
  docs/commanddocs.toml
  docs/commands.md
  src/main/kotlin/org/hyacinthbots/lilybot/LilyBot.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/Cleanups.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/GithubCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/GithubData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/Migrator.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV4.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Github.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: T: new feature, T: feature enhancement

#283 Add welcome channels
  README.md
  build.gradle.kts
  libs.versions.toml
  src/main/kotlin/org/hyacinthbots/lilybot/LilyBot.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/Cleanups.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/WelcomeChannelCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/WelcomeChannelData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV4.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/StartupHooks.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: PRT: new-feature

#276 Shake up info commands
  README.md
  build.gradle.kts
  detekt.yml
  docs/usage-guide.md
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/UptimeCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/UptimeData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/InfoCommands.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: T: new feature, PRT: new-feature
