Repository HyacinthBots/LilyBot, pull requests merged in 2022-05, with the labels that each got.

#133 Rewrite say, remove DM functionality
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
Labels: PRT: refactor, final comment period

#134 Remove old guild data after 30 days or more
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/JoinLeaveDetection.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MemberJoinLeave.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
Labels: PRT: new-feature, final comment period

#136 Update docs for 3.2.0
  docs/development-guide.md
  docs/hosting-guide.md
  docs/usage-guide.md
Labels: PRT: documentation

#135 3.2.0 Release
  CONTRIBUTING.md
  Dockerfile
  build.gradle.kts
  commands.toml
  docs/changelogs/3.2.0.md
  docs/commands.md
  docs/development-guide.md
  docs/hosting-guide.md
  docs/usage-guide.md
  libs.versions.toml
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/JoinLeaveDetection.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MemberJoinLeave.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/CustomCommands.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Github.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/ResponseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Constants.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
Labels: PRT: release-staging

#142 Add image capability to logging embeds
  docs/commands.md
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
Labels: PRT: new-feature

#143 3.2.1 release
  build.gradle.kts
  docs/changelogs/3.2.1.md
  docs/commands.md
  docs/release-checklist.md
  libs.versions.toml
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Github.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
Labels: final comment period, PRT: release-staging

#145 Fix errors when deleting threads
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
Labels: PRT: Trivial

#146 Hypothetical fix for public utility commands not adding on join
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/StartupHooks.kt
Labels: PRT: bug-fix, final comment period

#149 Get channel default archive times
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
Labels: PRT: Trivial

#147 Only use one check block instead of multiple
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MemberJoinLeave.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadControl.kt
Labels: PRT: Trivial

#148 Add reason to un-ban embeds
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
Labels: PRT: Trivial

#144 [WIP] Rewrite Configuration System
  build.gradle.kts
  libs.versions.toml
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/ConfigExtension.kt
Labels: PRT: new-feature, PRT: refactor

#156 Fix erros if message deleted is too long
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
Labels: PRT: bug-fix, PRT: Trivial

#153 Allow say messages/embeds to be edited after sending them
  docs/commands.md
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
Labels: PRT: new-feature, final comment period
