Repository HyacinthBots/LilyBot, pull requests merged in 2022-06, with the labels that each got.

#157 Refactor Report to use modals
  build.gradle.kts
  libs.versions.toml
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
Labels: PRT: refactor, final comment period

#160 Support PluralKit with message deletions
  src/main/kotlin/net/irisshaders/lilybot/api/pluralkit/PluralKit.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
Labels: PRT: new-feature, final comment period

#161 Help and info commands!
  Dockerfile
  build.gradle.kts
  docs/commanddocs.toml
  docs/commands.md
  docs/development-guide.md
  docs/usage-guide.md
  libs.versions.toml
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/InfoCommands.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Constants.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/docs/CommandDocs.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/docs/DocsGenerator.kt
Labels: PRT: documentation, final comment period

#158 Add commands to make a channel "image only"
  docs/commanddocs.toml
  docs/commands.md
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
Labels: PRT: new-feature, final comment period

#163 Create command doc headers, like the old command docs
  docs/commanddocs.toml
  docs/commands.md
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/InfoCommands.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/docs/CommandDocs.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/docs/DocsGenerator.kt
Labels: PRT: documentation

#162 Release 3.3.0
  .github/workflows/release.yml
  Dockerfile
  build.gradle.kts
  docs/changelogs/3.3.0.md
  docs/commanddocs.toml
  docs/commands.md
  docs/development-guide.md
  docs/usage-guide.md
  libs.versions.toml
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/api/pluralkit/PluralKit.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Github.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/InfoCommands.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Constants.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/docs/CommandDocs.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/docs/DocsGenerator.kt
Labels: PRT: release-staging

#165 Release 3.3.1
  build.gradle.kts
  docs/changelogs/3.3.1.md
  docs/commanddocs.toml
  docs/commands.md
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/api/pluralkit/PluralKit.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/docs/DocsGenerator.kt
Labels: PRT: release-staging

#167 Support PluralKit in support threads
  src/main/kotlin/net/irisshaders/lilybot/api/pluralkit/PluralKit.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
Labels: PRT: compatibility/support

#166 Reminder commands
  docs/commanddocs.toml
  docs/commands.md
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RemindMe.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
Labels: PRT: new-feature

#168 Clean up message building
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MemberJoinLeave.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/InfoCommands.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/StartupHooks.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/ResponseHelper.kt
Labels: PRT: refactor

#180 Make use of inline on functions to increase performance
  src/main/kotlin/net/irisshaders/lilybot/api/pluralkit/PluralKit.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/ResponseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/docs/DocsGenerator.kt
Labels: PRT: Trivial

#187 Refactor/fix #181
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MemberJoinLeave.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/StartupHooks.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadControl.kt
Labels: PRT: bug-fix, PRT: refactor

#179 Fix #95
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RemindMe.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
Labels: PRT: bug-fix

#185 Role Menu Rewrite
  docs/commanddocs.toml
  docs/commands.md
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
Labels: PRT: refactor

#189 Fix errors when tag bodies are too long
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
Labels: PRT: bug-fix

#190 Improve permission check functions
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
Labels: PRT: refactor

#176 Reminder improvements
  docs/commanddocs.toml
  docs/commands.md
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RemindMe.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
Labels: PRT: refactor

#188 Release v3.4.0
  build.gradle.kts
  docs/changelogs/3.4.0.md
  docs/commanddocs.toml
  docs/commands.md
  docs/release-checklist.md
  src/main/kotlin/net/irisshaders/lilybot/api/pluralkit/PluralKit.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MemberJoinLeave.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RemindMe.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/StartupHooks.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/ResponseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/docs/DocsGenerator.kt
Labels: PRT: release-staging

#191 Fix log uploading in threads
  src/main/kotlin/net/irisshaders/lilybot/api/pluralkit/PluralKit.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
Labels: PRT: bug-fix
