Repository HyacinthBots/LilyBot, pull requests merged in 2022-12, with the labels that each got.

#313 Additional permission checks
  libs.versions.toml
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/LockingCommands.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/ModerationCommands.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Github.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GuildAnnouncements.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Reminders.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Tags.kt
Labels: S: urgent, PRT: compatibility/support

#307 Add Public member logs
  docs/commanddocs.toml
  docs/commands.md
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/PublicMemberLogData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/Migrator.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV3.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MemberLogging.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: PRT: new-feature, T: feature enhancement

#314 Release v4.5.0
  build.gradle.kts
  detekt.yml
  docs/changelogs/4.4.2.md
  docs/changelogs/4.5.0.md
  docs/commanddocs.toml
  docs/commands.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  libs.versions.toml
  settings.gradle.kts
  src/main/kotlin/org/hyacinthbots/lilybot/LilyBot.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/UptimeCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/PublicMemberLogData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/Migrator.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV3.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MemberLogging.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MessageEdit.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/LockingCommands.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/ModerationCommands.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Github.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GuildAnnouncements.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/InfoCommands.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Reminders.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/StartupHooks.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Tags.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/ResponseHelper.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_ConfigUtils.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_PermissionUtils.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
  src/main/resources/comit_hash.txt
Labels: PRT: release-staging

#315 Switch to using KordEx provided modals
  libs.versions.toml
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GuildAnnouncements.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ThreadControl.kt
Labels: PRT: refactor
