Repository HyacinthBots/LilyBot, pull requests merged in 2022-03, with the labels that each got.

#93 Readme badges
  README.md
Labels: enhancement, PR status: under review

#98 De-duplicate some of the database checking code
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/JoinLeaveEvent.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageEvents.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Moderation.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Utilities.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/ResponseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
Labels: enhancement, PR status: under review, refactor

#97 Switch database to MongoDB
  .editorconfig
  CONTRIBUTING.md
  README.md
  build.gradle.kts
  docs/changelogs/2.0.0.md
  docs/changelogs/2.0.1.md
  docs/changelogs/2.1.0.md
  docs/changelogs/3.0.0.md
  docs/commands.md
  docs/development-guide.md
  docs/hosting-guide.md
  docs/installation-guide.md
  docs/lily-logo-transparent.png
  docs/usage-guide.md
  gradle/wrapper/gradle-wrapper.properties
  libs.versions.toml
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/database/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/database/DatabaseManager.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/JoinLeaveEvent.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageEvents.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Moderation.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/CustomCommands.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Github.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Utilities.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/ResponseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Constants.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
Labels: enhancement, PR status: under review, new-feature, refactor

#101 Refactor the warn command
  docs/commands.md
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
Labels: enhancement, PR status: under review, refactor

#102 Do more code de-duplication
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MemberJoinLeave.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Github.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/ResponseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
Labels: enhancement, PR status: under review, refactor
