Repository HyacinthBots/LilyBot, pull requests merged in 2022-04, with the labels that each got.

#100 3.0.0 Release
  .editorconfig
  CONTRIBUTING.md
  README.md
  build.gradle.kts
  docs/changelogs/2.0.0.md
  docs/changelogs/2.0.1.md
  docs/changelogs/2.1.0.md
  docs/changelogs/3.0.0.md
  docs/commands.md
  docs/development-guide.md
  docs/hosting-guide.md
  docs/installation-guide.md
  docs/lily-logo-transparent.png
  docs/usage-guide.md
  gradle/wrapper/gradle-wrapper.properties
  libs.versions.toml
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/database/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/database/DatabaseManager.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MemberJoinLeave.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Moderation.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/CustomCommands.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Github.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/ResponseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Constants.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
Labels: enhancement, new-feature, refactor, final comment period

#109 Fix commands erroring when used in DM's
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
Labels: PRT: bug-fix, S: urgent

#108 Create pull request policy.
  CONTRIBUTING.md
Labels: PRT: documentation, T: enhancement

#106 Feature: Nickname Requests
  build.gradle.kts
  gradle.properties
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
Labels: T: enhancement, PRT: new-feature, final comment period

#117 Improve say logging
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
Labels: PRT: refactor

#113 Fix threads not inviting mods when support team config isn't set
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
Labels: PRT: bug-fix, final comment period, S: urgent

#105 Add locking commands
  docs/commands.md
  docs/development-guide.md
  docs/hosting-guide.md
  docs/usage-guide.md
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
Labels: PRT: new-feature, final comment period

#112 Switch to mclo.gs for Log Uploading
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/LogUploading.kt
Labels: PRT: refactor, final comment period

#110 Create Tag commands. Deprecate Custom Commands
  docs/commands.md
  docs/resources/oauth2example.png
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/CustomCommands.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
Labels: T: enhancement, PRT: new-feature, final comment period

#111 Refactor the functions for the database
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MemberJoinLeave.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
Labels: PRT: refactor

#119 Detekt 2 electric boogaloo
  build.gradle.kts
  detekt.yml
  libs.versions.toml
  settings.gradle.kts
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MemberJoinLeave.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/CustomCommands.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Github.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/ResponseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
Labels: T: enhancement

#121 Fix bugs with report
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
Labels: PRT: bug-fix, S: urgent

#122 Add basic error handling to log upload
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/LogUploading.kt
Labels: PRT: bug-fix

#120 3.1.0 Release
  CONTRIBUTING.md
  README.md
  build.gradle.kts
  detekt.yml
  docs/changelogs/3.1.0.md
  docs/commands.md
  docs/development-guide.md
  docs/hosting-guide.md
  docs/resources/oauth2example.png
  docs/usage-guide.md
  gradle.properties
  libs.versions.toml
  settings.gradle.kts
  src/main/kotlin/net/irisshaders/lilybot/LilyBot.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/config/Config.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MemberJoinLeave.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/CustomCommands.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Github.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/Tags.kt
  src/main/kotlin/net/irisshaders/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/DatabaseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/ResponseHelper.kt
  src/main/kotlin/net/irisshaders/lilybot/utils/_Utils.kt
Labels: final comment period, PRT: release-staging
