Repository HyacinthBots/LilyBot, pull requests merged in 2022-09, with the labels that each got.

#235 Allow moderators to remove all a users reminders
  docs/changelogs/4.0.0.md
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Reminders.kt
Labels: PRT: new-feature

#237 Add an option to publicly log moderation actions
  docs/commanddocs.toml
  docs/commands.md
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV1.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/ConfigOptions.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: PRT: new-feature

#242 Utility logging
  docs/commanddocs.toml
  docs/commands.md
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/ConfigCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV1.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/ConfigOptions.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/ConfigType.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MemberLogging.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Tags.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: T: enhancement, PRT: new-feature

#260 Run cleanups on a scheduler
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/GalleryChannelData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/GuildLeaveTimeData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/RemindMeData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/RoleMenuData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/StatusData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/TagsData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/ThreadData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/WarnData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/StartupHooks.kt
Labels: T: enhancement, PRT: new-feature

#262 Implement a command to reset the database entirely for a guild
  src/main/kotlin/org/hyacinthbots/lilybot/database/Cleanups.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/GalleryChannelCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/LogUploadingBlacklistCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/RemindMeCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/ThreadsCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/ThreadData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/Migrator.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV2.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/StartupHooks.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ThreadControl.kt
Labels: T: enhancement

#236 Log when message tags are sent
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Tags.kt
Labels: PRT: new-feature

#266 Check required roles can be ponged before adding to database
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: PRT: bug-fix

#265 Granular optional config
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MemberLogging.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MessageEdit.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Tags.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: PRT: bug-fix

#267 Guild announcements
  docs/commanddocs.toml
  docs/commands.md
  libs.versions.toml
  src/main/kotlin/org/hyacinthbots/lilybot/LilyBot.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GuildAnnouncements.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: T: enhancement

#268 Release 4.1.0
  build.gradle.kts
  docs/changelogs/4.1.0.md
  docs/changelogs/changelog-template.md
  docs/commanddocs.toml
  docs/commands.md
  libs.versions.toml
  src/main/kotlin/org/hyacinthbots/lilybot/LilyBot.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/Cleanups.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/GalleryChannelCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/LogUploadingBlacklistCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/RemindMeCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/ThreadsCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/GalleryChannelData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/GuildLeaveTimeData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/RemindMeData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/RoleMenuData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/StatusData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/TagsData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/ThreadData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/WarnData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/Migrator.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV1.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV2.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/ConfigOptions.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MemberLogging.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MessageEdit.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/TemporaryModeration.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/TerminalModeration.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GuildAnnouncements.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Reminders.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/StartupHooks.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Tags.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: PRT: release-staging
