Repository HyacinthBots/LilyBot, pull requests merged in 2023-01, with the labels that each got.

#320 Fix auto-punishment based on warn command
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/ModerationCommands.kt
Labels: PRT: bug-fix

#318 Rewrite thread inviting
  src/main/kotlin/org/hyacinthbots/lilybot/LilyBot.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/AutoThreadingCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/ConfigCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/ThreadsCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/AutoThreadingData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/GithubData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/ThreadData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/Migrator.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV1.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV2.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV3.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV4.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV1.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV2.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV3.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV4.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV5.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/ConfigOptions.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/ConfigType.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/AutoThreading.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/ModThreadInviting.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/StartupHooks.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ThreadControl.kt
Labels: PRT: refactor

#322 4.6.0
  .editorconfig
  README.md
  build.gradle.kts
  docs/changelogs/4.6.0.md
  docs/commanddocs.toml
  docs/commands.md
  libs.versions.toml
  src/main/kotlin/org/hyacinthbots/lilybot/LilyBot.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/AutoThreadingCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/ConfigCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/ThreadsCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/AutoThreadingData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/GithubData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/ThreadData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/Migrator.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV1.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV2.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV3.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/config/configV4.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV1.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV2.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV3.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV4.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV5.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/ConfigOptions.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/ConfigType.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/AutoThreading.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/LogUploading.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MessageDelete.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/MessageEdit.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/ModThreadInviting.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/ThreadInviter.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/LockingCommands.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/ModerationCommands.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/Report.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GalleryChannel.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/GuildAnnouncements.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/InfoCommands.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/PublicUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Reminders.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/RoleMenu.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/StartupHooks.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Tags.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ThreadControl.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/ResponseHelper.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_PermissionUtils.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/docs/CommandDocs.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/docs/DocsGenerator.kt
  src/main/resources/kordex/mappings/config.toml
Labels: PRT: release-staging

#323 Fix mods being invited to all threads, and old thread checking
  docs/commands.md
  libs.versions.toml
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/AutoThreadingData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/Migrator.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV5.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV6.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/config/Config.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/AutoThreading.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/ModThreadInviting.kt
Labels: PRT: bug-fix, S: urgent

#326 Release 4.6.1
  build.gradle.kts
  docs/changelogs/2.x.x/2.0.0.md
  docs/changelogs/2.x.x/2.0.1.md
  docs/changelogs/2.x.x/2.1.0.md
  docs/changelogs/3.x.x/3.0.0.md
  docs/changelogs/3.x.x/3.1.0.md
  docs/changelogs/3.x.x/3.1.1.md
  docs/changelogs/3.x.x/3.2.0.md
  docs/changelogs/3.x.x/3.2.1.md
  docs/changelogs/3.x.x/3.2.2.md
  docs/changelogs/3.x.x/3.3.0.md
  docs/changelogs/3.x.x/3.3.1.md
  docs/changelogs/3.x.x/3.3.2.md
  docs/changelogs/3.x.x/3.3.3.md
  docs/changelogs/3.x.x/3.4.0.md
  docs/changelogs/3.x.x/3.4.1.md
  docs/changelogs/3.x.x/3.4.2.md
  docs/changelogs/3.x.x/3.4.3.md
  docs/changelogs/3.x.x/3.4.4.md
  docs/changelogs/3.x.x/3.4.5.md
  docs/changelogs/3.x.x/3.4.6.md
  docs/changelogs/3.x.x/3.5.0.md
  docs/changelogs/3.x.x/3.5.1.md
  docs/changelogs/3.x.x/3.5.2.md
  docs/changelogs/3.x.x/3.5.3.md
  docs/changelogs/3.x.x/3.5.4.md
  docs/changelogs/3.x.x/3.5.5.md
  docs/changelogs/4.x.x/4.0.0.md
  docs/changelogs/4.x.x/4.0.1.md
  docs/changelogs/4.x.x/4.1.0.md
  docs/changelogs/4.x.x/4.1.1.md
  docs/changelogs/4.x.x/4.2.0.md
  docs/changelogs/4.x.x/4.3.0.md
  docs/changelogs/4.x.x/4.4.0.md
  docs/changelogs/4.x.x/4.4.1.md
  docs/changelogs/4.x.x/4.4.2.md
  docs/changelogs/4.x.x/4.5.0.md
  docs/changelogs/4.x.x/4.6.0.md
  docs/changelogs/4.x.x/4.6.1.md
  libs.versions.toml
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/moderation/ModerationCommands.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/ResponseHelper.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: PRT: release-staging

#327 Fix reminder messages
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Reminders.kt
Labels: PRT: bug-fix

#328 Add news channel publishing
  docs/commands.md
  src/main/kotlin/org/hyacinthbots/lilybot/LilyBot.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/Cleanups.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/NewsChannelPublishingCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/NewsChannelPublishingData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/Migrator.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV7.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/NewsChannelPublishing.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
Labels: T: new feature, PRT: new-feature

#329 Add autothreading view command
  docs/commands.md
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/AutoThreading.kt
Labels: T: feature enhancement

#330 Release v4.6.3
  .editorconfig
  .github/workflows/release.yml
  build.gradle.kts
  docs/changelogs/4.x.x/4.6.3.md
  docs/commands.md
  libs.versions.toml
  settings.gradle.kts
  src/main/kotlin/org/hyacinthbots/lilybot/LilyBot.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/Cleanups.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/collections/NewsChannelPublishingCollection.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/entities/NewsChannelPublishingData.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/Migrator.kt
  src/main/kotlin/org/hyacinthbots/lilybot/database/migrations/main/mainV7.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/events/AutoThreading.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/InfoCommands.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/ModUtilities.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/NewsChannelPublishing.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/Reminders.kt
  src/main/kotlin/org/hyacinthbots/lilybot/extensions/util/StartupHooks.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Constants.kt
  src/main/kotlin/org/hyacinthbots/lilybot/utils/_Utils.kt
  updateWebDocs.sh
Labels: PRT: release-staging
